name: Go Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.3'

    - name: Install dependencies
      run: go mod download

    - name: Test
      run: go test -v ./...

    # This test file has been moved to examples directory and is now part of the main tests
    # - name: Run Test Progress Demo
    #  run: go run examples/test_indicators/test_progress.go